#ifndef VARIAD_CPP_HVV_DEFER
#define VARIAD_CPP_HVV_DEFER

#define HVV_EMPTY()
#define HVV_DEFER_1(F) F HVV_EMPTY()
#define HVV_DEFER_2(F) F HVV_EMPTY HVV_EMPTY()()
#define HVV_DEFER_3(F) F HVV_EMPTY HVV_EMPTY HVV_EMPTY()()()
#define HVV_DEFER_4(F) F HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY()()()()
#define HVV_DEFER_5(F) F HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY()()()()()
#define HVV_DEFER_6(F) F HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY()()()()()()
#define HVV_DEFER_7(F) F HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY()()()()()()()
#define HVV_DEFER_8(F) F HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY HVV_EMPTY()()()()()()()()

#endif

